### PR TITLE
Cc 40 extend documentation

### LINKED ISSUE #40: Extend read the docs documentation
Add template's functionalities and commands to the read the docs documentation

**Reason**
It is the most convenient for users to read and search all relevant documentation in Read the Docs and refer to the README files for the first direction.

**Design**

- Move content from cookiecutter README into the Read the Docs
  - Generate documentation for Makefile commands
  - Separate functions of the cookiecutter and the project clearly
  - ~Add credits.rst which has Authors, Contributors and License~
- ~Add Changelog~
- Simplify cookiecutter readme

**Acceptance Criteria**
- Above content added to the documentation

**Outcome**
- Documentation updated
- Read the docs dev docs are updated

### PR DESCRIPTION
**Pull request by sertansenturk**
## Description

Closes #40 

## Motivation and Context

See #40 

## How Has This Been Tested?

Readthedocs: https://cookiecutter-ds-docker.readthedocs.io/en/cc-40-extend-documentation/index.html

## Types of changes

- [x] Documentation (extending or improving to describe the repo)

## Checklist

- [x] Docs have been added / updated

### CODE REVIEW

**Comment by sertansenturk** [comment]
@hedonistrh can you proof read https://cookiecutter-ds-docker.readthedocs.io/en/cc-40-extend-documentation/index.html?

**Comment by halil-erdogan** [comment]
Hey @sertansenturk , thanks for the documentation. 💯 🪂 

I have few advices 
- [For this part](https://cookiecutter-ds-docker.readthedocs.io/en/cc-40-extend-documentation/cookiecutter_template.html#installing-cookiecutter), I would say Debian Linux instead of Ubuntu Linux. Because `apt-get` should work with other Debian based distros.
- Maybe we can add version of Python in the documentation. _(Which version of Python will come with this ie. 3.7 etc.)_
- For the  [make test](https://cookiecutter-ds-docker.readthedocs.io/en/cc-40-extend-documentation/cookiecutter_template.html#running-tests-locally), we can add something like that _"if you did not run the make before, make test will install required things"_

**Comment by sertansenturk** [comment]
Thanks for the comments! See my responses below:

- Clarified as Debían- based Linux distributions 
- will add the Python version as well as the names of the built Docker images
- this is a side effect, and adding this much of detail could be confusing.  They should use the documented `make build` instead. 

Please let me know if this is not clear from the current text.

**Comment by halil-erdogan** [comment]
Thanks for fast response. Now everything looks fine for me. 💯

**Review by halil-erdogan — COMMENTED** [review]
Thanks for the changes.

**Review by halil-erdogan — DISMISSED** [review]
I think latest version explains everything pretty well. So, we can approve the PR. Thanks a lot for the documentation. 🦉

**Review by halil-erdogan — APPROVED** [review]
Thanks for clarification. 🦁

**Pull request merged**
